from random import randint
from secrets import randbelow, token_urlsafe

from django.conf import settings
from django.core.mail import send_mail


def generate_url():
    length = randbelow(30)
    while(length < 15):
        length = randbelow(30)
    string = token_urlsafe(length)
    return string


def verification_mailto(receiver, token):
    subject = "Email verification of NiT account"
    url = "http://localhost:8000/accounts/validate/" + token
    body = """
    This is a email confermation message!\n
    This message is autogenerated! Please Do Not reply!\n
    Click on this link to verify your Email:\n\t""" + url + """\n\n
    Ignore this message if this was not what you were expecting!\n\n"""
    
    sender = "Narula Institute Of Technology"
    user = "djangoemaildem0@gmail.com"
    password = "djang0123"
    try:
        send_mail(subject, body, sender, receiver, fail_silently=False, auth_user=user, auth_password=password,)
        return True
    except:
        return False


def get_cute_image():
    image_urls = {
        1: "https://image.flaticon.com/icons/svg/141/141737.svg",
        2: "https://image.flaticon.com/icons/svg/141/141746.svg",
        3: "https://image.flaticon.com/icons/svg/141/141739.svg",
        4: "https://image.flaticon.com/icons/svg/141/141744.svg",
        5: "https://image.flaticon.com/icons/svg/141/141742.svg",
        6: "https://image.flaticon.com/icons/svg/141/141745.svg",
        7: "https://image.flaticon.com/icons/svg/141/141738.svg",
        8: "https://image.flaticon.com/icons/svg/141/141736.svg",
        9: "https://image.flaticon.com/icons/svg/141/141747.svg",
        10: "https://image.flaticon.com/icons/svg/141/141740.svg",
        11: "https://image.flaticon.com/icons/svg/141/141741.svg",
        12: "https://image.flaticon.com/icons/svg/141/141743.svg"
    }
    num = randint(1, 12)
    return image_urls[num]
