# Generated by Django 2.1.1 on 2018-09-01 18:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(default='', max_length=20)),
                ('school_name', models.CharField(default='', max_length=50)),
                ('passing_year', models.CharField(default='0000', max_length=4)),
                ('school_address', models.CharField(default='', max_length=100)),
                ('score', models.FloatField(default=0.0)),
                ('achivements', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Class12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(default='', max_length=20)),
                ('school_name', models.CharField(default='', max_length=50)),
                ('passing_year', models.CharField(default='0000', max_length=4)),
                ('school_address', models.CharField(default='', max_length=100)),
                ('score', models.FloatField(default=0.0)),
                ('achivements', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Contributions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_magazine_paper', models.CharField(default='', max_length=1000)),
                ('annual_magazine_event', models.CharField(default='', max_length=1000)),
                ('wall_magazine_paper', models.CharField(default='', max_length=1000)),
                ('wall_magazine_event', models.CharField(default='', max_length=1000)),
                ('technical_academic_awards', models.CharField(default='', max_length=1000)),
                ('paper_publication', models.CharField(default='', max_length=500)),
                ('oncampus', models.CharField(default='', max_length=1000)),
                ('offcampus', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('blood_grp', models.CharField(default='', max_length=3)),
                ('guardian', models.CharField(default='', max_length=50)),
                ('perm_add', models.CharField(default='', max_length=50)),
                ('loc_guardian', models.CharField(default='', max_length=50)),
                ('loc_add', models.CharField(default='', max_length=50)),
                ('land_phone', models.IntegerField(null=True)),
                ('mobile_no', models.IntegerField(default='000')),
                ('is_lateral', models.BooleanField(default=False)),
                ('diploma_score', models.FloatField(max_length='50', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtracurricularActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_skill', models.CharField(default='', max_length=50)),
                ('aptitude', models.CharField(default='', max_length=50)),
                ('mock_interview', models.BooleanField(default=False)),
                ('online_test', models.BooleanField(default=False)),
                ('gate_exam', models.BooleanField(default=False)),
                ('cat_exam', models.BooleanField(default=False)),
                ('saraswati_puja', models.BooleanField(default=False)),
                ('vishwakarma_puja', models.BooleanField(default=False)),
                ('industry_visit_1', models.CharField(default='', max_length=50)),
                ('industry_visit_1_date', models.DateField(default=django.utils.timezone.now)),
                ('industry_visit_2', models.CharField(default='', max_length=50)),
                ('industry_visit_2_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SeminarWorkshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('organiser', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(default=' ', max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(default=' ', max_length=50)),
                ('class_roll_no', models.IntegerField(default=0)),
                ('registration_no', models.IntegerField(default=0)),
                ('admision_no', models.IntegerField(default=0)),
                ('stream', models.CharField(default=' ', max_length=20)),
                ('batch', models.IntegerField(default=0)),
                ('is_registered', models.BooleanField(default=False)),
                ('is_varified', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=70)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='seminarworkshop',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AddField(
            model_name='extracurricularactivity',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AddField(
            model_name='details',
            name='card_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AddField(
            model_name='contributions',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AddField(
            model_name='class12',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AddField(
            model_name='class10',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
