# Generated by Django 2.1.1 on 2018-09-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='class_roll_no',
            new_name='roll_no',
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(default='', max_length=12),
        ),
    ]
