# Generated by Django 2.1.1 on 2018-09-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20180902_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mentor',
            field=models.CharField(default=' ', max_length=15),
        ),
    ]
