# Generated by Django 2.1.1 on 2018-09-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20180906_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFills',
            fields=[
                ('student', models.CharField(default=' ', max_length=15, primary_key=True, serialize=False)),
                ('is_gen_deatils_filled', models.BooleanField(default=False)),
                ('is_univ_details_filled', models.BooleanField(default=False)),
                ('is_sem1_filled', models.BooleanField(default=False)),
                ('is_sem2_filled', models.BooleanField(default=False)),
                ('is_sem3_filled', models.BooleanField(default=False)),
                ('is_sem4_filled', models.BooleanField(default=False)),
                ('is_sem5_filled', models.BooleanField(default=False)),
                ('is_sem6_filled', models.BooleanField(default=False)),
                ('is_sem7_filled', models.BooleanField(default=False)),
                ('is_sem8_filled', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='class10',
            name='id',
        ),
        migrations.RemoveField(
            model_name='class12',
            name='id',
        ),
        migrations.RemoveField(
            model_name='contributions',
            name='id',
        ),
        migrations.RemoveField(
            model_name='details',
            name='id',
        ),
        migrations.RemoveField(
            model_name='extracurricularactivity',
            name='id',
        ),
        migrations.RemoveField(
            model_name='seminarworkshop',
            name='id',
        ),
        migrations.AlterField(
            model_name='class10',
            name='student',
            field=models.CharField(default=' ', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='class12',
            name='student',
            field=models.CharField(default=' ', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='student',
            field=models.CharField(default=' ', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='details',
            name='card_no',
            field=models.CharField(default=' ', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='extracurricularactivity',
            name='student',
            field=models.CharField(default=' ', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seminarworkshop',
            name='attendee',
            field=models.CharField(default=' ', max_length=15, primary_key=True, serialize=False),
        ),
    ]
