# Generated by Django 2.1.1 on 2018-09-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20180923_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='admision_no',
            new_name='admission_no',
        ),
    ]
