# Generated by Django 2.1.1 on 2018-09-29 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20180923_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class10',
            old_name='achivements',
            new_name='achievements',
        ),
        migrations.RenameField(
            model_name='class12',
            old_name='achivements',
            new_name='achievements',
        ),
    ]
