# Generated by Django 2.1.5 on 2019-01-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20180929_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dept',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='stream',
            field=models.CharField(default=' ', max_length=1),
        ),
    ]
