# Generated by Django 2.1.5 on 2019-02-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20190112_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='guardian_mobile_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='details',
            name='mobile_no',
            field=models.CharField(default='', max_length=10),
        ),
    ]
