# Generated by Django 2.1.5 on 2019-03-01 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20190217_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='roll_no',
            new_name='univ_roll_no',
        ),
    ]
