# Generated by Django 2.1.5 on 2019-03-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20190301_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_no',
            field=models.CharField(default=' ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_no',
            field=models.CharField(default=' ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='univ_roll_no',
            field=models.CharField(default=' ', max_length=20, null=True),
        ),
    ]
