# Generated by Django 2.1.5 on 2019-03-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20190301_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='surname',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
