# Generated by Django 2.1.5 on 2019-03-05 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_auto_20190305_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counselings',
            fields=[
                ('student', models.CharField(default=' ', max_length=15, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('topic', models.CharField(default=' ', max_length=30)),
            ],
        ),
    ]
