# Generated by Django 2.1.5 on 2019-03-24 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_counselings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarsWorkshops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.CharField(default=' ', max_length=15)),
                ('name', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('organiser', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='SeminarWorkshop',
        ),
        migrations.AddField(
            model_name='contributions',
            name='contributions',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
