# Generated by Django 2.1.5 on 2019-03-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_auto_20190324_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
