# Generated by Django 2.1.5 on 2019-04-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_auto_20190331_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extracurricularactivity',
            name='aptitude',
        ),
        migrations.RemoveField(
            model_name='extracurricularactivity',
            name='soft_skill',
        ),
        migrations.AddField(
            model_name='extracurricularactivity',
            name='aptitude_attend',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extracurricularactivity',
            name='aptitude_conduct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extracurricularactivity',
            name='soft_skill_attend',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extracurricularactivity',
            name='soft_skill_conduct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='extracurricularactivity',
            name='industry_visit_1_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='extracurricularactivity',
            name='industry_visit_2_date',
            field=models.DateField(null=True),
        ),
    ]
