# Generated by Django 2.1.5 on 2019-04-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_auto_20190407_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributions',
            name='offcampus',
        ),
        migrations.RemoveField(
            model_name='contributions',
            name='oncampus',
        ),
        migrations.AlterField(
            model_name='contributions',
            name='annual_magazine_event',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='annual_magazine_paper',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='contributions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='paper_publication',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='technical_academic_awards',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='wall_magazine_event',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='wall_magazine_paper',
            field=models.TextField(default=''),
        ),
    ]
