# Generated by Django 2.1.5 on 2019-04-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_auto_20190414_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributions',
            name='technical_contests',
            field=models.TextField(default=''),
        ),
    ]
