# Generated by Django 2.1 on 2019-10-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_auto_20191012_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.CharField(default=' ', max_length=15, primary_key=True, serialize=False)),
                ('batch', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
