# Generated by Django 2.1.1 on 2018-10-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject_and_marks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semmarks',
            old_name='attentence',
            new_name='attendance',
        ),
    ]
