# Generated by Django 2.1.1 on 2018-10-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_and_marks', '0002_auto_20181025_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField(default=0)),
                ('sub1', models.CharField(default='', max_length=8)),
                ('sub2', models.CharField(default='', max_length=8)),
                ('sub3', models.CharField(default='', max_length=8)),
                ('sub4', models.CharField(default='', max_length=8)),
                ('sub5', models.CharField(default='', max_length=8)),
                ('sub6', models.CharField(blank=True, default='', max_length=8, null=True)),
                ('lab1', models.CharField(default='', max_length=8)),
                ('lab2', models.CharField(default='', max_length=8)),
                ('lab3', models.CharField(default='', max_length=8)),
                ('lab4', models.CharField(default='', max_length=8)),
                ('lab5', models.CharField(blank=True, default='', max_length=8, null=True)),
            ],
        ),
    ]
