# Generated by Django 2.1.5 on 2019-01-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_and_marks', '0003_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='sem',
        ),
        migrations.AlterField(
            model_name='subjects',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
