# Generated by Django 2.1.5 on 2019-01-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_and_marks', '0004_auto_20190111_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='dept',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='subjects',
            name='sem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subjects',
            name='stream',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
