# Generated by Django 2.1.5 on 2019-01-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_and_marks', '0006_subjects_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semmarks',
            name='lab1_internal',
            field=models.FloatField(blank=True, default=0.0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='semmarks',
            name='lab2_internal',
            field=models.FloatField(blank=True, default=0.0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='semmarks',
            name='lab3_internal',
            field=models.FloatField(blank=True, default=0.0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='semmarks',
            name='lab4_internal',
            field=models.FloatField(blank=True, default=0.0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='semmarks',
            name='lab5_internal',
            field=models.FloatField(blank=True, default=0.0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='semmarks',
            name='sub1_internal',
            field=models.FloatField(blank=True, default=0.0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='semmarks',
            name='sub2_internal',
            field=models.FloatField(blank=True, default=0.0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='semmarks',
            name='sub3_internal',
            field=models.FloatField(blank=True, default=0.0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='semmarks',
            name='sub4_internal',
            field=models.FloatField(blank=True, default=0.0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='semmarks',
            name='sub5_internal',
            field=models.FloatField(blank=True, default=0.0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='semmarks',
            name='sub6_internal',
            field=models.FloatField(blank=True, default=0.0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='lab3',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='lab4',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='sub4',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='sub5',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
    ]
