# Generated by Django 2.1.5 on 2019-01-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_and_marks', '0007_auto_20190112_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semmarks',
            name='lab4',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='semmarks',
            name='lab4_marks',
            field=models.FloatField(blank=True, default=0.0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='semmarks',
            name='lab5',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='semmarks',
            name='lab5_marks',
            field=models.FloatField(blank=True, default=0.0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='semmarks',
            name='sub5',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='semmarks',
            name='sub5_marks',
            field=models.FloatField(blank=True, default=0.0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='semmarks',
            name='sub6',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='semmarks',
            name='sub6_marks',
            field=models.FloatField(blank=True, default=0.0, max_length=5, null=True),
        ),
    ]
