# Generated by Django 2.1.5 on 2019-03-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_and_marks', '0008_auto_20190112_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('dept_code', models.CharField(default='', max_length=5, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(default='', max_length=30)),
                ('hod', models.CharField(default=' ', max_length=15)),
                ('btech', models.BooleanField(default=True)),
                ('mtech', models.BooleanField(default=False)),
                ('diploma', models.BooleanField(default=False)),
            ],
        ),
    ]
