# Generated by Django 2.1.5 on 2019-06-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_and_marks', '0009_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='', max_length=5)),
                ('stream', models.CharField(default='', max_length=1)),
                ('batch_name', models.CharField(default='', max_length=11)),
            ],
        ),
    ]
