# Generated by Django 2.1.1 on 2018-09-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='mentees1',
            field=models.CharField(default='0-0', max_length=27),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mentees2',
            field=models.CharField(default='0-0', max_length=27),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mentees3',
            field=models.CharField(default='0-0', max_length=27),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mentees4',
            field=models.CharField(default='0-0', max_length=27),
        ),
    ]
