# Generated by Django 2.1.5 on 2019-01-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_auto_20180923_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='mentees1',
            field=models.CharField(default='0-0', max_length=27, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mentees2',
            field=models.CharField(default='0-0', max_length=27, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mentees3',
            field=models.CharField(default='0-0', max_length=27, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mentees4',
            field=models.CharField(default='0-0', max_length=27, null=True),
        ),
    ]
