# Generated by Django 2.1 on 2019-09-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_remove_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, default="{% static 'teachers/img/profile.jpg'%}", null=True, upload_to='profile_pic/'),
        ),
    ]
